const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Persist,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.SetMuted
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{ChãoSala1: 0},
	{Sólido: 0},
	{Estante1: 0},
	{SofáSala1: 0},
	{Sprite: 0},
	{MesaSala1: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Teclado: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{direcao: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{Persistir: 0},
	{Sprite4: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite151: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{Sprite21: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{PlanoDeFundoEmBlocos9: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{PlanoDeFundoEmBlocos10: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Mouse: 0},
	{Sprite42: 0},
	{Sprite19: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{perguntas: 0},
	{respprocess: 0},
	{resphd: 0},
	{respfonte: 0},
	{respcooler: 0},
	{Sprite49: 0},
	{respPular: 0},
	{Sprite46: 0},
	{Sprite50: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{voltar: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite47: 0},
	{Sprite60: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite61: 0},
	{Sprite43: 0},
	{Sprite48: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Sprite33: 0},
	{Sprite150: 0},
	{Texto: 0},
	{VoltarBTN: 0},
	{Sprite64: 0},
	{prosseguirBTN: 0},
	{Sprite65: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Texto7: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite69: 0},
	{Sprite66: 0},
	{Sprite70: 0},
	{Texto8: 0},
	{Sprite72: 0},
	{Sprite71: 0},
	{Texto9: 0},
	{Texto10: 0},
	{Texto11: 0},
	{Sprite73: 0},
	{Sprite74: 0},
	{Texto12: 0},
	{Áudio: 0},
	{Sprite75: 0},
	{Texto13: 0},
	{Texto14: 0},
	{Sprite77: 0},
	{Sprite78: 0},
	{Sprite79: 0},
	{Sprite80: 0},
	{Sprite81: 0},
	{Respvirus: 0},
	{Sprite82: 0},
	{resReinicirPC: 0},
	{ResReiniciarNet: 0},
	{Sprite83: 0},
	{Texto15: 0},
	{Sprite85: 0},
	{Texto16: 0},
	{Sprite87: 0},
	{Sprite88: 0},
	{Sprite89: 0},
	{Sprite90: 0},
	{Sprite91: 0},
	{Sprite92: 0},
	{Sprite93: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Sprite96: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{Sprite99: 0},
	{Sprite100: 0},
	{Sprite101: 0},
	{Sprite84: 0},
	{Sprite102: 0},
	{Sprite103: 0},
	{Texto17: 0},
	{Sprite104: 0},
	{Texto18: 0},
	{Texto19: 0},
	{toqueRafael: 0},
	{Sprite105: 0},
	{Texto20: 0},
	{Texto21: 0},
	{Texto22: 0},
	{Sprite76: 0},
	{Sprite106: 0},
	{Sprite107: 0},
	{Texto23: 0},
	{Sprite86: 0},
	{Sprite108: 0},
	{Sprite109: 0},
	{Sprite20: 0},
	{Sprite56: 0},
	{Sprite110: 0}
];

self.InstanceType = {
	ChãoSala1: class extends self.ITiledBackgroundInstance {},
	Estante1: class extends self.ISpriteInstance {},
	SofáSala1: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	MesaSala1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite151: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos9: class extends self.ITiledBackgroundInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos10: class extends self.ITiledBackgroundInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	perguntas: class extends self.ISpriteInstance {},
	respprocess: class extends self.ISpriteInstance {},
	resphd: class extends self.ISpriteInstance {},
	respfonte: class extends self.ISpriteInstance {},
	respcooler: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	respPular: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	voltar: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite150: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	VoltarBTN: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	prosseguirBTN: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	Texto10: class extends self.ITextInstance {},
	Texto11: class extends self.ITextInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Texto12: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Texto13: class extends self.ITextInstance {},
	Texto14: class extends self.ITextInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	Respvirus: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	resReinicirPC: class extends self.ISpriteInstance {},
	ResReiniciarNet: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	Texto15: class extends self.ITextInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Texto16: class extends self.ITextInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	Sprite101: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	Texto17: class extends self.ITextInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	Texto18: class extends self.ITextInstance {},
	Texto19: class extends self.ITextInstance {},
	toqueRafael: class extends self.ISpriteInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Texto20: class extends self.ITextInstance {},
	Texto21: class extends self.ITextInstance {},
	Texto22: class extends self.ITextInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite106: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	Texto23: class extends self.ITextInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	Sprite109: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite110: class extends self.ISpriteInstance {}
}